config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users , :controllers => {:registrations => "users/registrations"}

   root 'blood_glucose_levels#index'

   resources :blood_glucose_levels do
    get 'reports', on: :collection
    post 'daily_report', on: :collection
    post 'monthly_report', on: :collection
    post 'month_to_date_report', on: :collection
   end

end

app/models/blood_glucose_level.rb
class GlucoseLevelValidator < ActiveModel::Validator
  def validate(record)
  	current_date = Date.today
    unless BloodGlucoseLevel.where(:user_id=>record.send(:user_id)).date_range(current_date,current_date+1).count <= 4 
      record.errors[:base] << "No more than 4 entries on a given day"
    end
  end
end

class BloodGlucoseLevel < ActiveRecord::Base
	belongs_to :user
	scope :date_range, ->(start_date,end_date){where(["recorded_at >= ? and recorded_at < ?",start_date, end_date])}
	scope :min_level, ->{select("MIN(data) as min_level")}
	scope :avg_level, ->{select("AVG(data) as avg_level")}
	scope :max_level, ->{select("MAX(data) as max_level")}

	validates_with GlucoseLevelValidator


	def self.today_levels(current_usr_id)
		current_date = Date.today
		BloodGlucoseLevel.where(:user_id=>current_usr_id).date_range(current_date,current_date+1)
	end

	def self.monthly_glucose_levels(selected_dt,current_usr_id)
	  selected_date =   Date.parse(selected_dt)
      start_date =  Date.new(selected_date.year,selected_date.month)
      end_date = selected_date.end_of_month + 1
      BloodGlucoseLevel.where(:user_id=>current_usr_id).date_range(start_date,end_date)
	end

	def self.daily_glucose_levels(selected_dt,current_usr_id)
	  start_date =   Date.parse(selected_dt)
      end_date = start_date + 1
      BloodGlucoseLevel.where(:user_id=>current_usr_id).date_range(start_date,end_date)
	end

	def self.month_to_date_glucose_levels(selected_dt,current_usr_id)
	  selected_date =   Date.parse(selected_dt)
      start_date =  Date.new(selected_date.year,selected_date.month)
      end_date = selected_date + 1
      BloodGlucoseLevel.where(:user_id=>current_usr_id).date_range(start_date,end_date)
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blood_glucose_levels, dependent: :destroy
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blood_glucose_levels_controller.rb
class BloodGlucoseLevelsController < ApplicationController
  before_action :set_blood_glucose_level, only: [:show, :edit, :update, :destroy]

  # GET /blood_glucose_levels
  # GET /blood_glucose_levels.json
  def index
    @blood_glucose_level = BloodGlucoseLevel.new
    @blood_glucose_levels = BloodGlucoseLevel.today_levels(current_user.id)
  end

  # GET /blood_glucose_levels/1
  # GET /blood_glucose_levels/1.json
  def show
  end

  # GET /blood_glucose_levels/new
  def new
    @blood_glucose_level = BloodGlucoseLevel.new
  end

  # GET /blood_glucose_levels/1/edit
  def edit
  end

  # POST /blood_glucose_levels
  # POST /blood_glucose_levels.json
  def create
    @blood_glucose_level = BloodGlucoseLevel.new(blood_glucose_level_params.merge(:recorded_at => Time.zone.now,:user_id=>current_user.id))

    respond_to do |format|
      if @blood_glucose_level.save
        format.html { redirect_to root_path, notice: 'Blood glucose level was successfully created.' }
      else
       format.html { redirect_to root_path, notice: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_glucose_levels/1
  # PATCH/PUT /blood_glucose_levels/1.json
  def update
    respond_to do |format|
      if @blood_glucose_level.update(blood_glucose_level_params)
        format.html { redirect_to @blood_glucose_level, notice: 'Blood glucose level was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood_glucose_level }
      else
        format.html { render :edit }
        format.json { render json: @blood_glucose_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_glucose_levels/1
  # DELETE /blood_glucose_levels/1.json
  def destroy
    @blood_glucose_level.destroy
    respond_to do |format|
      format.html { redirect_to blood_glucose_levels_url, notice: 'Blood glucose level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reports
      @blood_glucose_levels = BloodGlucoseLevel.today_levels(current_user.id)
  end

  def daily_report
      @blood_glucose_levels = BloodGlucoseLevel.daily_glucose_levels(params[:selected_date],current_user)
      respond_to do |format|
        format.js
      end
  end

  def monthly_report
      @blood_glucose_levels = BloodGlucoseLevel.monthly_glucose_levels(params[:selected_date],current_user)
      respond_to do |format|
        format.js
      end
  end

  def month_to_date_report
      @blood_glucose_levels = BloodGlucoseLevel.month_to_date_glucose_levels(params[:selected_date],current_user)
      respond_to do |format|
        format.js
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_glucose_level
      @blood_glucose_level = BloodGlucoseLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_glucose_level_params
      params.require(:blood_glucose_level).permit(:user, :data, :recorded_at)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:mobile,:address,:role_id])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name,:mobile,:address,:role_id])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def get_user_types
		Role.all.collect{|role| [role.name, role.id]}
	end

	def get_min_level(blood_glucose_levels)
		return 0 unless blood_glucose_levels.present?
		blood_glucose_levels.min_level.map(&:min_level).first
	end

	def get_avg_level(blood_glucose_levels)
		return 0 unless blood_glucose_levels.present?
		blood_glucose_levels.avg_level.map(&:avg_level).first
	end

	def get_max_level(blood_glucose_levels)
		return 0 unless blood_glucose_levels.present?
		blood_glucose_levels.max_level.map(&:max_level).first
	end
end

app/helpers/blood_glucose_levels_helper.rb
module BloodGlucoseLevelsHelper

	
end

app/views/blood_glucose_levels/_form.html.erb
<%= form_for(@blood_glucose_level) do |f| %>
  <% if @blood_glucose_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blood_glucose_level.errors.count, "error") %> prohibited this blood_glucose_level from being saved:</h2>

      <ul>
      <% @blood_glucose_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enter_glucose_level %><br>
    <%= f.number_field :data %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/blood_glucose_levels/_list.html.erb
<h3>Listing Blood Glucose Levels</h3>

<ul class="list-inline">
  <li><span class="label label-warning lb-lg">Min<span class="badge"><%=get_min_level(@blood_glucose_levels)%>mg/dl</span></span></li>
  <li><span class="label label-success lb-lg">Avg<span class="badge"><%=get_avg_level(@blood_glucose_levels)%>mg/dl</span></span></li>
  <li><span class="label label-danger lb-lg">Max<span class="badge"><%=get_max_level(@blood_glucose_levels)%>mg/dl</span></span></li>
</ul>
<table class="table table-fixed table-striped">
  <thead>
    <tr>
      <th>SN</th>
      <th>Glucose Level</th>
      <th>Recorded at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_glucose_levels.each_with_index do |blood_glucose_level,index| %>
      <tr>
        <td><%=index+1%></td>
        <td><%= blood_glucose_level.data %>mg/dl</td>
        <td><%= blood_glucose_level.recorded_at %></td>
        <td><%= link_to 'Edit', edit_blood_glucose_level_path(blood_glucose_level) %></td>
        <td><%= link_to 'Destroy', blood_glucose_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blood_glucose_levels/daily_report.js.erb
$("#report_div").html("<%= escape_javascript(render partial: 'list', locals: { items: @blood_glucose_levels } ) %>").show(); 

app/views/blood_glucose_levels/edit.html.erb
<h1>Editing Blood Glucose Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @blood_glucose_level %> |
<%= link_to 'Back', blood_glucose_levels_path %>

app/views/blood_glucose_levels/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<div class="jumbotron">
<%= render 'form' %>
</div>

<%= render 'list' %>

</div>

app/views/blood_glucose_levels/month_to_date_report.js.erb
$("#report_div").html("<%= escape_javascript(render partial: 'list', locals: { items: @blood_glucose_levels } ) %>").show(); 

app/views/blood_glucose_levels/monthly_report.js.erb
$("#report_div").html("<%= escape_javascript(render partial: 'list', locals: { items: @blood_glucose_levels } ) %>").show(); 

app/views/blood_glucose_levels/new.html.erb
<h1>Blood Glucose Levels</h1>

<%= render 'form' %>

<%= link_to 'Back', blood_glucose_levels_path %>

app/views/blood_glucose_levels/reports.html.erb
<div class="container-fluid text-center">
<div class="row content">
<div class="col-sm-2 sidenav">
      <p><a data-toggle="tab" href="#home" onclick = 'javascript:$("#report_div").hide()'>Daily Report</a></p>
      <p><a data-toggle="tab" href="#menu1" onclick = 'javascript:$("#report_div").hide()'>Month to Date Report</a></p>
      <p><a data-toggle="tab" href="#menu2" onclick = 'javascript:$("#report_div").hide()'>Monthly Report</a></p>
</div>
<div class="col-sm-10 text-center">
<div class="tab-content">
  <div id="home" class="tab-pane fade in active">
    <div class="jumbotron">

    <h3>Daily Report</h3>Please select date
    <%= form_tag(daily_report_blood_glucose_levels_path,remote: true,:method => :post) do %>
    <input type="date" name="selected_date">
    <%= submit_tag "Report",:class=>"btn btn-info"%>
    <% end %>

    </div>  
  </div>
  <div id="menu1" class="tab-pane fade">
  <div class="jumbotron">
    <h3>Month to Date Report</h3>
      Please select date
      <%= form_tag(month_to_date_report_blood_glucose_levels_path,remote: true,:method => :post) do %>
    <input type="date" name="selected_date">
    <%= submit_tag "Report",:class=>"btn btn-info"%>
    <% end %>  

    </div>
  </div>
  <div id="menu2" class="tab-pane fade">
  <div class="jumbotron">
    <h3>Monthly Report</h3>
    <%= form_tag(monthly_report_blood_glucose_levels_path,remote: true,:method => :post) do %>
    <input type="date" name="selected_date">
    <%= submit_tag "Report",:class=>"btn btn-info"%>
    <% end %> 
    </div>
  </div>
</div>
<div id="report_div"></div> 
 </div>
</div> 
</div>  

app/views/blood_glucose_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @blood_glucose_level.data %>
</p>

<p>
  <strong>Recorded at:</strong>
  <%= @blood_glucose_level.recorded_at %>
</p>

<%= link_to 'Edit', edit_blood_glucose_level_path(@blood_glucose_level) %> |
<%= link_to 'Back', blood_glucose_levels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlucoseTracker</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Sweety Glucose Tracker</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', '/'%></li>
        <% if user_signed_in? %>
        <li><%= link_to 'Report', reports_blood_glucose_levels_path%></li>
        <% end %> 
      </ul>
      <ul class="nav navbar-nav navbar-right">    	
      		<% if user_signed_in? %>
  				<li><%= link_to 'Edit profile', edit_user_registration_path%> </li>
 				<li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
			<% else %>
 				<li><%= link_to "Sign up", new_user_registration_path  %> </li>
  				<li><%= link_to "Login", new_user_session_path, :class=> "glyphicon glyphicon-log-in" %></li>
			<% end %>   	
      </ul>
    </div>
    <div>
    <% if user_signed_in? %>
    (Logged in as <b><%= current_user.name %></b>)
    <% end %> 
    </div>
  </div>
</nav>
<div class="container-fluid text-center">
      <%= yield %>
</div>

<footer class="navbar-fixed-bottom row-fluid text-center">
  <p>Copy right</p>
</footer>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>